[package]
name = "rurune"
version = "0.1.0"
authors = ["Linden Chiu <hchiu87@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web =  { version="2.0", features=["openssl"] }
actix-rt = "1.0"
actix-files = "0.2.1"
awc = "1.0.1"

bytes = "0.5.4"
dotenv = "0.15.0"
futures = "0.3.4"
json = "0.12.4"
listenfd = "0.3"
openssl = "0.10.29"
reqwest = { version = "0.10.4", features = ["json"] }
rustls = "0.17.0"
serde = "1.0.106"
serde_derive = "1.0.106"
serde_json = "1.0.52"
tokio = { version = "0.2.2", features = ["full"] }
twilio-async = "0.2.0"

